# Generated by Django 4.0.5 on 2022-07-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('documento', models.CharField(max_length=100, null=True, verbose_name='Cédula')),
                ('correo', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('compañia', models.CharField(max_length=100, null=True, verbose_name='Empresa')),
            ],
        ),
    ]
